repos:

  # Ruff (Lint + Format)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args:
          - --fix

      - id: ruff-format


  # Vulture (only backend/main.py)
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture
        args:
          - backend/main.py
          - --ignore-names
          - home,chat,upload_pdf,ask_document,generate_quiz
        pass_filenames: false


  # Pylint
  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.6
    hooks:
      - id: pylint
        args:
          - --init-hook=import sys;sys.path.append("backend")
        additional_dependencies:
          - fastapi
          - pydantic
          - requests
          - pypdf
          - chromadb


  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests


 # Bandit Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args:
          - -r
          - backend
          - -x
          - backend/venv
        additional_dependencies:
          - pbr
        pass_filenames: false

  # Basic Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml


  # Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args:
          - --exclude=venv,.venv

    # Secret Scanning
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks

    # Pyupgrade Python Modernization
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        language_version: python3.13
        args:
          - --py313-plus
